yarnPath: ".yarn/releases/yarn-berry.cjs"
enableStrictSsl: false
nodeLinker: "pnp"
packageExtensions:
  'vuepress@*':
    peerDependencies:
      '@vuepress/shared-utils': '*'
  'vue-server-renderer@*':
    dependencies:
      'vue': '*'

